import {
    IonPage,
    IonCard,
    IonCardHeader,
    IonCardContent,
    IonTitle,
    IonCardSubtitle,
    IonIcon,
    IonCardTitle,
    IonFab,
    IonFabButton,
    IonModal,
    IonItem,
    IonText,
    IonInput,
    IonDatetime,
    IonLabel,
    IonSelect,
    IonSelectOption,
    IonTextarea,
    IonButton,
    IonToolbar, IonBackdrop, IonButtons,
    IonContent,
    IonItemOption,
    IonListHeader,
    IonCheckbox,
    IonItemOptions,
    IonItemSliding,
    IonList,
    IonHeader,
    IonSpinner
} from "@ionic/vue";

export default {
    IonPage,
    IonCard,
    IonCardHeader,
    IonCardContent,
    IonTitle,
    IonCardSubtitle,
    IonIcon,
    IonCardTitle,
    IonFab,
    IonFabButton,
    IonModal,
    IonItem,
    IonText,
    IonInput,
    IonDatetime,
    IonLabel,
    IonSelect,
    IonSelectOption,
    IonTextarea,
    IonButton,
    IonToolbar, IonBackdrop, IonButtons,
    IonContent,
    IonItemOption,
    IonListHeader,
    IonCheckbox,
    IonItemOptions,
    IonItemSliding,
    IonList,
    IonHeader,
    IonSpinner

}